os: linux
language: node_js
cache:
  npm: false
  directories:
    - "~/.pnpm-store"

before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

jobs:
  include:
    - stage: release
      node_js: lts/*
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - pnpm run build
        - pnpm run lint
        - pnpm run test
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      deploy:
        provider: script
        cleanup: false
        skip_cleanup: true
        script: pnpx semantic-release
